language: go

go:
  - 1.7.x

install:
  - go get -v github.com/Masterminds/glide
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo
  - glide install

script: go build