sudo: required
language: go

services:
  - docker

go:
  - 1.7.x

install:
  - go get -v github.com/Masterminds/glide
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

script:
  - mkdir -p $HOME/.glide
  - mkdir -p $HOME/gopath/src/github.ibm.com/projectcalico/
  - cp -r ../libcalico-go $HOME/gopath/src/github.ibm.com/projectcalico/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.ibm.com/projectcalico/libcalico-go
  - cd $TRAVIS_BUILD_DIR
  - make ut